checks:
    php:
      code_rating: true
      duplication: false
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        php:
            version: 7.1.0
filter:
    excluded_paths:
        - tests/*
        - docs/*
        - vendor/*
        - example.php
